name: Deploy Flashcards App to Hostinger

on: 
  push:
    branches: 
      - main

jobs: 
  ftp-deploy:
    name: Upload backend to Hostinger via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      # first job
      - name: Deploy Laravel backend via FTP
        uses: carlosbuitragosan/ftp-deploy-action@master
        with: 
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          server-dir: ./
          exclude: |
            **/.git*
            **/node_modules/**
            **/tests/**
            **/storage/logs/**
            **/.env*
            **/vendor/**
            README.md
          state-name: .ftp-deploy-sync.json
    